# Generated by Django 5.1.5 on 2025-01-25 00:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Timer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField()),
                ("scheduled_time", models.DateTimeField()),
                ("is_fired", models.BooleanField(default=False)),
            ],
        ),
    ]
